# Generated by Django 2.2.14 on 2020-08-23 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_personaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
