# Generated by Django 2.2.14 on 2020-08-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200823_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
