# Generated by Django 2.2.14 on 2020-08-29 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=100)),
                ('grades', models.TextField(default='')),
                ('start_date', models.DateField(default=datetime.datetime(2020, 8, 29, 14, 52, 30, 378236, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2020, 8, 29, 14, 52, 30, 378260, tzinfo=utc))),
            ],
        ),
    ]
